[package]
name = "png"
version = "0.16.7"
license = "MIT OR Apache-2.0"

description = "PNG decoding and encoding library in pure Rust"
categories = ["multimedia::images"]
authors = ["nwin <nwin@users.noreply.github.com>"]
repository = "https://github.com/image-rs/image-png.git"

edition = "2018"
include = [
    "/LICENSE-MIT",
    "/LICENSE-APACHE",
    "/README.md",
    "/CHANGES.md",
    "/src/",
    "/examples/",
    "/benches/",
]

[dependencies]
deflate = { version = "0.8.2", optional = true }
bitflags = "1.0"
crc32fast = "1.2.0"
[dependencies.miniz_oxide]
version = "0.4.1"
features = ["no_extern_crate_alloc"]

[dev-dependencies]
criterion = "0.3.1"
getopts = "0.2.14"
term = "0.6.1"
glob = "0.3"
rand = "0.7.0"

[dev-dependencies.glium]
version = "0.24"
features = ["glutin"]
default-features = false

[features]
png-encoding = ["deflate"]
default = ["png-encoding"]
unstable = []
benchmarks = []

[[bench]]
path = "benches/decoder.rs"
name = "decoder"
harness = false
